
const main_gameplay_events = [
    "Forward",
    "Back",
    "Strafe Left",
    "Strafe Right",
    "Move",
    "Look",
    "Left Attack/Block",
    "Right Attack/Block",
    "Activate",
    "Ready Weapon",
    "Tween Menu",
    "Toggle POV",
    "Zoom Out",
    "Zoom In",
    "Jump",
    "Sprint",
    "Shout",
    "Sneak",
    "Run",
    "Toggle Always Run",
    "Auto-Move",
    "Favorites",
    "Hotkey1",
    "Hotkey2",
    "Hotkey3",
    "Hotkey4",
    "Hotkey5",
    "Hotkey6",
    "Hotkey7",
    "Hotkey8",
    "Quicksave",
    "Quickload",
    "Wait",
    "Journal",
    "Pause",
    "Screenshot",
    "Multi-Screenshot",
    "Console",
    "CameraPath",
    "Quick Inventory",
    "Quick Magic",
    "Quick Stats",
    "Quick Map",
];

const menu_mode_events = [
    "Accept",
    "Cancel",
    "Up",
    "Down",
    "Left",
    "Right",
    "Left Stick",
    "Console",
];

const console_events = [
    "PickPrevious",
    "PickNext",
    "Up",
    "Down",
    "PageUp",
    "PageDown",
    "Console",
    "NextFocus",
    "PreviousFocus",
];

const gameplay_events_list = [
    main_gameplay_events,
    menu_mode_events,
    console_events,
];

var padkeys = [
    ['-', "0xff"],
    ['↑', "0x0001"],
    ['↓', "0x0002"],
    ['←', "0x0004"],
    ['→', "0x0008"],
    ['LT', "0x0009"],
    ['RT', "0x000a"],
    ['Left Stick', "0x000b"],
    ['Right Stick', "0x000c"],
    ['START', "0x0010"],
    ['BACK', "0x0020"],
    ['L3', "0x0040"],
    ['R3', "0x0080"],
    ['LB', "0x0100"],
    ['RB', "0x0200"],
    ['A', "0x1000"],
    ['B', "0x2000"],
    ['X', "0x4000"],
    ['Y', "0x8000"],
];

var keys = [
    ['-', "0xff"],
    ["Esc", "0x01"],
    ["1", "0x02"],
    ["2", "0x03"],
    ["3", "0x04"],
    ["4", "0x05"],
    ["5", "0x06"],
    ["6", "0x07"],
    ["7", "0x08"],
    ["8", "0x09"],
    ["9", "0x0a"],
    ["0", "0x0b"],
    ["-", "0x0c"],
    ["=", "0x0d"],
    ["Back Space", "0x0e"],
    ["Tab", "0x0f"],
    ["Q", "0x10"],
    ["W", "0x11"],
    ["E", "0x12"],
    ["R", "0x13"],
    ["T", "0x14"],
    ["Y", "0x15"],
    ["U", "0x16"],
    ["I", "0x17"],
    ["O", "0x18"],
    ["P", "0x19"],
    ["[", "0x1a"],
    ["]", "0x1b"],
    ["Enter", "0x1c"],
    ["Ctrl (左)", "0x1d"],
    ["A", "0x1e"],
    ["S", "0x1f"],
    ["D", "0x20"],
    ["F", "0x21"],
    ["G", "0x22"],
    ["H", "0x23"],
    ["J", "0x24"],
    ["K", "0x25"],
    ["L", "0x26"],
    [";", "0x27"],
    ["'", "0x28"],
    ["`", "0x29"],
    ["Shift (左)", "0x2a"],
    ["\\", "0x2b"],
    ["Z", "0x2c"],
    ["X", "0x2d"],
    ["C", "0x2e"],
    ["V", "0x2f"],
    ["B", "0x30"],
    ["N", "0x31"],
    ["M", "0x32"],
    [",", "0x33"],
    [".", "0x34"],
    ["/", "0x35"],
    ["Shift (右)", "0x36"],
    ["* (Numpad)", "0x37"],
    ["Alt (左)", "0x38"],
    ["Space", "0x39"],
    ["Caps Lock", "0x3a"],
    ["F1", "0x3b"],
    ["F2", "0x3c"],
    ["F3", "0x3d"],
    ["F4", "0x3e"],
    ["F5", "0x3f"],
    ["F6", "0x40"],
    ["F7", "0x41"],
    ["F8", "0x42"],
    ["F9", "0x43"],
    ["F10", "0x44"],
    ["Num Lock", "0x45"],
    ["Scroll Lock", "0x46"],
    ["7 (Numpad)", "0x47"],
    ["8 (Numpad)", "0x48"],
    ["9 (Numpad)", "0x49"],
    ["- (Numpad)", "0x4a"],
    ["4 (Numpad)", "0x4b"],
    ["5 (Numpad)", "0x4c"],
    ["6 (Numpad)", "0x4d"],
    ["+ (Numpad)", "0x4e"],
    ["1 (Numpad)", "0x4f"],
    ["2 (Numpad)", "0x50"],
    ["3 (Numpad)", "0x51"],
    ["0 (Numpad)", "0x52"],
    [". (Numpad)", "0x53"],
    ["F11", "0x57"],
    ["F12", "0x58"],
    ["F13", "0x64"],
    ["F14", "0x65"],
    ["F15", "0x66"],
    ["カナ", "0x70"],
    ["変換", "0x79"],
    ["無変換", "0x7b"],
    ["¥", "0x7d"],
    ["=", "0x8d"],
    ["^", "0x90"],
    ["@", "0x91"],
    [":", "0x92"],
    ["_", "0x93"],
    ["漢字", "0x94"],
    ["Stop", "0x95"],
    ["(Japan AX)", "0x96"],
    ["(J3100)", "0x97"],
    ["Enter (Numpad)", "0x9c"],
    ["Ctrl (右)", "0x9d"],
    [", (Numpad)", "0xb3"],
    ["/ (Numpad)", "0xb5"],
    ["Sys Rq", "0xb7"],
    ["Alt (右)", "0xb8"],
    ["Pause", "0xc5"],
    ["Home", "0xc7"],
    ["↑", "0xc8"],
    ["Page Up", "0xc9"],
    ["←", "0xcb"],
    ["→", "0xcd"],
    ["End", "0xcf"],
    ["↓", "0xd0"],
    ["Page Down", "0xd1"],
    ["Insert", "0xd2"],
    ["Delete", "0xd3"],
    ["Windows", "0xdb"],
    ["Windows", "0xdc"],
    ["Menu", "0xdd"],
    ["Power", "0xde"],
    ["Windows", "0xdf"]
];

var mousebuttons = [
    ['-', "0xff"],
    ['0x1', "0x1"],
    ['0x2', "0x2"],
    ['0x3', "0x3"],
    ['0x4', "0x4"],
    ['0x5', "0x5"],
    ['0x6', "0x6"],
    ['0x7', "0x7"],
    ['0x8', "0x8"],
    ['0x9', "0x9"],
    ['0xa', "0xa"],
];

const input_type_list = [
    "key",
    "mouse",
    "gamepad",
];

const input_types = {
    key: {
        name: "Keyboard",
        id: "key",
        keys: keys,
    },
    mouse: {
        name: "Mouse",
        id: "mouse",
        keys: mousebuttons,
    },
    gamepad: {
        name: "Gamepad",
        id: "pad",
        keys: padkeys,
    },
};

